name: states
description: States is Finite State Machine for Dart. You can define states of your application and reaction on transition between states
version: 1.1.0
homepage: https://github.com/vladimircores/States

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test:
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
