name: states
description: States is Finite State Machine for Dart. You can define states of your application and reaction on transition between states
version: 0.9.21
homepage: https://github.com/DQvsRA/States

environment:
  sdk: '>=2.6.1 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  build_web_compilers:
  build_runner:
