name: StateMachine
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://logico.tech
# author: vladimir.cores <vladimir.cores@logico.tech>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
