name: dart_machine
description: DartMachine is State Machine for Dart. You can define states of your application and reaction on transition between states
version: 0.1.4
homepage: https://github.com/DQvsRA/DartMachine
author: Vladimir Cores (Minkin) <vladimir.cores@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
